// Mocks generated by Mockito 5.0.16 from annotations
// in faturas/test/payment-options/view/screens/payment_options_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:faturas/payment-options/model/payment_option.dart' as _i4;
import 'package:faturas/payment-options/repository/rest/payment_options_rest_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUri_0 extends _i1.Fake implements Uri {}

/// A class which mocks [PaymentOptionsRestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentOptionsRestService extends _i1.Mock
    implements _i2.PaymentOptionsRestService {
  MockPaymentOptionsRestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Uri get paymentOptionsUrl =>
      (super.noSuchMethod(Invocation.getter(#paymentOptionsUrl),
          returnValue: _FakeUri_0()) as Uri);
  @override
  _i3.Future<List<_i4.PaymentOption>> fetchPaymentOptions() =>
      (super.noSuchMethod(Invocation.method(#fetchPaymentOptions, []),
              returnValue:
                  Future<List<_i4.PaymentOption>>.value(<_i4.PaymentOption>[]))
          as _i3.Future<List<_i4.PaymentOption>>);
  @override
  String toString() => super.toString();
}
